server:
  port: 10010
spring:
  application:
    name: leyou-gateway

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

zuul:
  prefix: /api
  routes:
    ##路由到item微服务
    item-service : /item/**
    ##路由到搜索微服务
    search-service : /search/**
# ignored-services: upload-service

