server:
  port: 10010
spring:
  application:
    name: leyou-gateway

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

zuul:
  prefix: /api
  routes:
    item-service : /item-service/**

