server:
  port: 8087

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      ##客户端链接注册中心的URL地址
      defaultZone: http://127.0.0.1:10086/eureka/
    ##是否注册到eureka上
    register-with-eureka: true
    ##是否需要从eureka上获取注册信息
    fetch-registry: true
    ##心跳检测检测与续约时间
    registry-fetch-interval-seconds: 30
  instance:
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
    ###Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 5
    ####Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 15

leyou:
  jwt:
    secret: leyou@Login(Auth}*^31)&Yang% # 登录校验的密钥
    pubKeyPath: E:\\tmp\\rsa\\rsa.pub # 公钥地址
    priKeyPath: E:\\tmp\\rsa\\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName : LY_TOKEN