server:
  port: 10086

spring:
  application:
    name: leyou-registry
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    ##因为自己是为注册中心，不需要自己注册自己【集群的时候需要设置为true】
    register-with-eureka: true
    ##因为自己是为注册中心，不需要检索服务,拉取服务
    fetch-registry: true
  server:
      ##关闭掉eureka 的自我保护机制,无法链接 eureka-client中的服务,就将服务剔除! 2s检测一次
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 2000
